### ISSUE TITLE
Crash with specific buffer.

### ISSUE THREAD

**Issue by phuongtran7** [mzaks/FlexBuffers-CSharp#2]
Hi,

I'm having a little weird crash with this specific buffer order. Whenever there are more than 11 element in the buffer, the C# library just crashes at line 673 (`var dif = key[j] - key2.Buffer[indirectOffset + j];`) in the `FlxValue.cs`. And the crash only appears with this buffers as I tested with a much larger buffers that has around 80 fields, it worked just fine. The other buffers also contains, some FixTypedVector and float value just like this one.

I'm using Flatbuffers version 1.12.0, installed with Vcpkg to create the buffer with C++:

```cpp
#include <iostream>
#include <vector>
#include <fstream>
#include "flatbuffers/flexbuffers.h"

int main()
{
    std::fstream output("Output_Crash.bin", std::ios::out | std::ios::binary);

    flexbuffers::Builder builder(256, flexbuffers::BuilderFlag::BUILDER_FLAG_NONE);

    const auto map_start = builder.StartMap();

    std::vector<float> engn1 = {1.1f, 1.2f};
    builder.FixedTypedVector("ENGN1", engn1.data(), engn1.size());
    builder.Float("radioaltitude", 1.0f);
    builder.Float("groundspeed", 1.0f);
    builder.Float("relativepitch", 1.0f);
    builder.Float("relativeheading", 1.0f);
    builder.Float("airspeed", 1.0f);
    builder.Float("altitude", 1.0f);
    builder.Float("verticalspeed", 1.0f);
    builder.Float("heading", 1.0f);
    builder.Float("pitch", 1.0f);
    builder.Float("roll", 1.0f);
    builder.Float("windsockheading", 1.0f);

    builder.EndMap(map_start);
    builder.Finish();

    output.write(reinterpret_cast<const char *>(builder.GetBuffer().data()), builder.GetSize());
    output.close();

    std::ifstream input("Output_Crash.bin", std::ios::binary);
    std::vector<uint8_t> buffer((std::istreambuf_iterator<char>(input)), std::istreambuf_iterator<char>());

    const auto data = flexbuffers::GetRoot(buffer.data(), buffer.size()).AsMap();

    auto ENGN1 = data["ENGN1"].AsFixedTypedVector();
    std::cout << "0: " << ENGN1[0].AsFloat() << "\n";
    std::cout << "1: " << ENGN1[1].AsFloat() << "\n";

    input.close();
    std::getchar();
}
```

And this is how I read the buffer with C#:

```csharp
using FlexBuffers;
using System;
using System.IO;

namespace Read_Flexbuffers_CSharp
{
    class Program
    {
        static void Main(string[] args)
        {
            //byte[] body = File.ReadAllBytes("Output.bin");
            byte[] body = File.ReadAllBytes("Output_Crash.bin");

            var flx = FlxValue.FromBytes(body).AsMap;
            var ENGN1 = flx["ENGN1"].AsVector;
            var radioaltitude = flx["radioaltitude"].AsDouble;
            var groundspeed = flx["groundspeed"].AsDouble;
            var relativepitch = flx["relativepitch"].AsDouble;
            var relativeheading = flx["relativeheading"].AsDouble;
            var airspeed = flx["airspeed"].AsDouble;
            var altitude = flx["altitude"].AsDouble;
            var verticalspeed = flx["verticalspeed"].AsDouble;
            var heading = flx["heading"].AsDouble;
            var pitch = flx["pitch"].AsDouble;
            var roll = flx["roll"].AsDouble;
        }
    }
}
```

The C# crashed when trying to access the `ENGN1` vector, even though that works on C++ side.

The attached file contains two binary file. The `Output.bin` is the binary that works on C# side. It is created by commenting out the `builder.Float("windsockheading", 1.0f);` in C++ when creating the file. And the `Output_Crash.bin` is the binary that crash the C# side, it has the `windsockheading` float value in there.

I can also provide the binary of the bigger buffer if needed. Thank you so much for your time and help.

[Binary.zip](https://github.com/mzaks/FlexBuffers-CSharp/files/5246893/Binary.zip)

**Comment by mzaks** [comment]
Hi @phuongtran7,

I think it is the same issue that we had with JS and Dart implementations.
I fixed it for those languages in following PR
https://github.com/google/flatbuffers/pull/6107

I can work on the fix for C# on this Sunday/Monday. 

If it is urgent for you.
Try to replace `ReadLong` with `ReadULong` on following line:
https://github.com/mzaks/FlexBuffers-CSharp/blob/master/FlexBuffers/FlxValue.cs#L415
It might already fix the crash. But there could be more places, or rather I know there are more places for a proper fix 😉. This is why I don't have the time to do it today.

**Comment by mzaks** [comment]
After further analysis, if the first change to `ReadULong` did not help with your crash, you can try to switch to `REadULong` also on this line:

https://github.com/mzaks/FlexBuffers-CSharp/blob/master/FlexBuffers/FlxValue.cs#L559

**Comment by phuongtran7** [comment]
Hi @mzaks

Thank you so much for quick help. The change to `ReadULong` on line 415 works perfectly for my case. Everything can be read now. I also changed the line 559 just to make sure and it worked too.

**Comment by mzaks** [comment]
Now I pushed a fix, which should address your issue as well as produce smaller buffers when serialised in C#.

Please let me know if there are any other issues.

And @phuongtran7 thank you very much for reporting this issue.
