### ISSUE TITLE
Support for uppercase keys?

### ISSUE THREAD

**Issue by M3n4p** [mzaks/FlexBuffers-CSharp#3]
Hi,
I had a very weird bug happening to me. It happens when you want to access a FlxMap with an uppercase key. I tested it in Unity and the code block below should reproduce the error.

The error thrown is: "Exception: No key 'T' could be found

```C#
Dictionary<string, object> dict = new Dictionary<string, object>();
dict.Add("aieorjhioa", "aerhj");
dict.Add("e98rh8d9i3qaktgr", "eaihjor");
dict.Add("T", "toeks");

byte[] testBytes = FlexBuffer.From(dict);
FlxMap map = FlxValue.FromBytes(testBytes).AsMap;

foreach (var pair in map)
{
    Debug.Log(map[pair.Key]);
}
```

In this case if every key is uppercase it seems to work but if only one key starts with a lowercase letter, an error is thrown.
It also happens with different keys. I also tried random keys starting with an uppercase letter, i.e. "Eriei905uheaioj", and some of them also throw the error whereas other ones work.

Thank you for your time and help.

**Comment by mzaks** [comment]
I will have a look, thanks for the test sample.

**Comment by M3n4p** [comment]
I tested it a bit further and switched all keys to lowercase and now the error is the same but happens on different parts of the buffer. The buffer gets created correctly and I also can use the Browser to look at it, it just doesn't recognize some keys.

**Comment by mzaks** [comment]
The keys needs to be sorted in ascending order when they are stored to buffer, because the look is basically a binary search. I think the sorting algorithm is broken when it comes to upper / lower case characters. From your simple test case I see the `"T"` is a t the last place but the utf8 code of upper `T` is actually smaller then the one of lower case chars, so I think this is where the bug is coming from.
So generally the data is stored but the keys are sorted badly and this is why lookup does not work properly. When you iterate over the keys or values, this will work fine.

**Comment by mzaks** [comment]
Ok I already found the problem, only the dynamic dictionary add is affected. I used the Standard sorting arlorithm, which sorts the capital letters in front of the lower case letters, where it should be sorted by UTF-8 codes and in this case the upper case chars are smaller then lower case chars.
Thanks for reporting I will make a patch and release a new version, also for FlexBuffers-Unity package

**Comment by M3n4p** [comment]
It also happens when I manually start maps, add keys and dynamically add values to a FlexBuffer without sorting the maps when I call EndMap(). I don't know if your fix also covers this.

**Comment by mzaks** [comment]
Could you please provide an example?
the method `EndMap()` on `FlexBuffer` is declared private, so I am not sure which use case you mean.

**Comment by M3n4p** [comment]
I changed the EndMap() method to public to build a FlexBuffer by reflection in a different class.

```C#
FlexBuffer buffer = new FlexBuffer();
var start = buffer.StartVector();

buffer.AddKey("aieorjhioa");
buffer.AddDynamic("aerhj");
buffer.AddKey("e98rh8d9i3qaktgr");
buffer.AddDynamic("eaihjor");
buffer.AddKey("T");
buffer.AddDynamic("toeks");

buffer.EndMap(start);

byte[] testBytes = buffer.Finish();
FlxMap map = FlxValue.FromBytes(testBytes).AsMap;

foreach (var pair in map)
{
      Debug.Log(map[pair.Key]);
}
```

**Comment by mzaks** [comment]
Ah I see, well you need to use `SortAndEndMap` now.

**Comment by mzaks** [comment]
I pushed the fix btw.

**Comment by mzaks** [comment]
I am closing this issue, please reopen if you see any problems with it.

**Comment by mzaks** [comment]
> I changed the EndMap() method to public to build a FlexBuffer by reflection in a different class.
> 
> ```cs
> FlexBuffer buffer = new FlexBuffer();
> var start = buffer.StartVector();
> 
> buffer.AddKey("aieorjhioa");
> buffer.AddDynamic("aerhj");
> buffer.AddKey("e98rh8d9i3qaktgr");
> buffer.AddDynamic("eaihjor");
> buffer.AddKey("T");
> buffer.AddDynamic("toeks");
> 
> buffer.EndMap(start);
> 
> byte[] testBytes = buffer.Finish();
> FlxMap map = FlxValue.FromBytes(testBytes).AsMap;
> 
> foreach (var pair in map)
> {
>       Debug.Log(map[pair.Key]);
> }
> ```

Btw. generally you can still use the `EndMap(start)` directly. You just need to make sure that you add your key value pairs in a proper order. In this particular case the pair with key `T` needs to go first. as 'T' = 84, 'a' = 97 and 'e' = 101, when it comes to UTF-8 code. And you also need to make sure for keys like `"maxim"` vs. `"maxValue"` where the second key is smaller then the first one.

**Comment by M3n4p** [comment]
The problem seems to be fixed. Thanks for the quick help.
